### ISSUE TITLE
Add predictions for Twitter followers

### ISSUE THREAD

**Issue by susiejojo** [MLH-Fellowship/Social-BERTerfly#13]
### Tasks to be done:

- [x] Fetch `n` followers by the username.

- [x] Fetch the top posts of each of the `n` followers.

- [x] for each follower, return prediction

- [x] return overall type prediction for `n` followers as json
